In [29]:
import numpy as np
import pandas as pd

from sklearn import preprocessing
from sklearn.model_selection import train_test_split

In [149]:
data = pd.read_csv('data\data2.csv', sep = ',')
print(data.info())
print(data.head())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27481 entries, 0 to 27480
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   textID         27481 non-null  object
 1   text           27480 non-null  object
 2   selected_text  27480 non-null  object
 3   sentiment      27481 non-null  object
dtypes: object(4)
memory usage: 858.9+ KB
None
       textID                                               text  \
0  cb774db0d1                I`d have responded, if I were going   
1  549e992a42      Sooo SAD I will miss you here in San Diego!!!   
2  088c60f138                          my boss is bullying me...   
3  9642c003ef                     what interview! leave me alone   
4  358bd9e861   Sons of ****, why couldn`t they put them on t...   

                         selected_text sentiment  
0  I`d have responded, if I were going   neutral  
1                             Sooo SAD  negative  
2                        

In [150]:
X = data['selected_text']
y = data['sentiment']

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 30, test_size = 0.15)

In [152]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import LinearSVC
from sklearn.pipeline import Pipeline

vectorizer = TfidfVectorizer()
X_train_final = vectorizer.fit_transform(X_train.values.astype('U'))


text_clf = LinearSVC()
text_clf.fit(X_train_final, y_train)

LinearSVC(C=1.0, class_weight=None, dual=True, fit_intercept=True,
          intercept_scaling=1, loss='squared_hinge', max_iter=1000,
          multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
          verbose=0)

In [153]:
X_test_final = vectorizer.transform(X_test.values.astype('U'))
predictions = text_clf.predict(X_test_final)

In [154]:
from sklearn.metrics import confusion_matrix, accuracy_score

print(accuracy_score(y_test, predictions))
print(confusion_matrix(y_test, predictions))

0.831918505942275
[[ 952  186   32]
 [ 144 1365  119]
 [  72  140 1113]]


In [158]:
import pickle

with open('vectorizer.pkl', 'wb') as f:
    pickle.dump(vectorizer, f)

with open('sentiment_classifier.pkl', 'wb') as f:
    pickle.dump(text_clf, f)

In [157]:
phrase = vectorizer.transform([str("ok")])
print(text_clf.predict(phrase))

['neutral']


In [159]:
print(X_train)
print(y_train)

4757                                                 wrong
26306                                                  fun
19587    We`re running out of things to tweet to you.  ...
12824       yay  i`ll do you a heart mk shout in a sec pam
3875                                              I`d love
                               ...                        
500                                                  wack.
12077    cant decide on wht i wanna do with the rest of...
15277                                             iloveyou
4517     Possible case of H1N1 at Ft. Knox (KY) http://...
5925                                                thanks
Name: selected_text, Length: 23358, dtype: object
4757     negative
26306    positive
19587     neutral
12824     neutral
3875     positive
           ...   
500      negative
12077     neutral
15277    positive
4517      neutral
5925     positive
Name: sentiment, Length: 23358, dtype: object
