In [1]:
import numpy as np
import pandas as pd
from sklearn import preprocessing
from sklearn.model_selection import train_test_split

In [2]:
#DIR = "C:\\Users\\fpa\\Documents\\dataEngineering-SentimentAnalysis\\model-learning"

data = pd.read_csv('data\data.csv', sep = ';')

In [3]:
data = data.set_index('PhraseId')
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 156060 entries, 1 to 156060
Data columns (total 3 columns):
 #   Column      Non-Null Count   Dtype 
---  ------      --------------   ----- 
 0   SentenceId  156060 non-null  int64 
 1   Phrase      156060 non-null  object
 2   Sentiment   156060 non-null  int64 
dtypes: int64(2), object(1)
memory usage: 4.8+ MB


In [4]:
data.head()
#In data file 0-negative/1-Some negative/2-Neutral/3-Some positive/4-positive
#In our data 0-negative/1-neutral/2-postive

data['Sentiment'] = data['Sentiment'].map({0: 0, 1: 0, 2: 1, 3: 2, 4: 2})


In [5]:
X = data['Phrase']
y = data['Sentiment']
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 30, test_size = 0.15)

In [6]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import LinearSVC
from sklearn.pipeline import Pipeline

vectorizer = TfidfVectorizer()
X_train_final = vectorizer.fit_transform(X_train)


text_clf = LinearSVC()

text_clf.fit(X_train_final, y_train)


LinearSVC(C=1.0, class_weight=None, dual=True, fit_intercept=True,
          intercept_scaling=1, loss='squared_hinge', max_iter=1000,
          multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
          verbose=0)

In [7]:
X_test_final = vectorizer.transform(X_test)
predictions = text_clf.predict(X_test_final)

In [8]:
from sklearn.metrics import confusion_matrix, accuracy_score

print(accuracy_score(y_test, predictions))
print(confusion_matrix(y_test, predictions))

0.7405271476782435
[[3281 1588  236]
 [1095 9653 1176]
 [ 197 1782 4401]]


In [9]:
import pickle

with open('vectorizer.pkl', 'wb') as f:
    pickle.dump(vectorizer, f)

with open('sentiment_classifier.pkl', 'wb') as f:
    pickle.dump(text_clf, f)

In [26]:
phrase = vectorizer.transform([str("a sweetness , clarity and emotional openness")])
print(text_clf.predict(phrase))

[2]


In [24]:
print(X_train)
print(y_train)

PhraseId
34289                          his difficult , endless work
14801     -LRB- as well as a serious debt to The Road Wa...
92737                                          this premise
125868         a sweetness , clarity and emotional openness
30741              too much exploitation and too little art
                                ...                        
96054                     someone made off with your wallet
66456                                          recreational
46221                                     far superior film
98805     the most entertaining moments here are uninten...
48046     this was your introduction to one of the great...
Name: Phrase, Length: 132651, dtype: object
PhraseId
34289     0
14801     1
92737     1
125868    2
30741     0
         ..
96054     0
66456     1
46221     2
98805     2
48046     2
Name: Sentiment, Length: 132651, dtype: int64
